# Generated by Django 3.1.1 on 2020-09-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
