# Generated by Django 3.1.1 on 2020-09-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booked'), (1, 'No Show'), (2, 'Seen')], default=0),
        ),
    ]
