# Generated by Django 3.1.1 on 2020-10-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_appointment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Schedule'), (2, 'No show'), (3, 'Completed')], default=0),
        ),
    ]
