# Generated by Django 3.1.1 on 2020-09-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_appointment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('respiration', models.IntegerField()),
                ('height', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
            ],
        ),
    ]
