# Generated by Django 3.1.1 on 2020-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_auto_20201022_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
