# Generated by Django 3.1.1 on 2020-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
