# Generated by Django 3.1.1 on 2020-11-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_auto_20201102_1618'),
        ('Appointments', '0004_auto_20201103_1833'),
    ]

    operations = [
    ]
